### ISSUE TITLE
Breaking Update in App Store - Deprecated UIWebView APIs. FBSDKLogin please upgrade 4.39.1 to 5.5.0

### ISSUE THREAD

**Issue by eleomilagrosa** [roughike/flutter_facebook_login#174]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

[Change Log](https://github.com/facebook/facebook-objc-sdk/blob/master/CHANGELOG.md?fbclid=IwAR3VsU9pi7ix2hDrR06QvlB6jlfEksUj1JR2AxQx-loT1PGiT8nWIyizaIQ)

5.5.0
2019-08-30 | Full Changelog

Changed
Replaced UIWebView with WKWebView as Apple will stop accepting submissions of apps that use UIWebView APIs
Added support for Catalyst
Fixed
Various bug fixes

**Comment by chynnasevilleno** [comment]
@roughike Giving this a bump! :)

**Comment by cpboyd** [comment]
@eleomilagrosa PR #169 already exists to fix this.

Until it's merged in, you should be able to modify your `pubspec.yaml` to:
```
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login.git
      ref: 16ecb49
```
