### ISSUE TITLE
[Flutter for Web] This package does not work when compiled for web.

### ISSUE THREAD

**Issue by brianschardt** [roughike/flutter_facebook_login#196]
This package does not work when compiled for web. Is there a way to make this work. 
I know this is how you tell if it is compiled for web or not. 
```
import 'package:flutter/foundation.dart';

if (kIsWeb) {

} else {

}

**Comment by brianschardt** [comment]
any updates on this?

**Comment by Kiruel** [comment]
![Screenshot 2019-12-18 at 17 38 45](https://user-images.githubusercontent.com/8250175/71105151-4ea20d00-21bd-11ea-9080-6fcf54d4ac66.png)
And on the pub it say web compatible, we should remove if it not the case.

**Comment by serragnoli** [comment]
Unfortunately I had to remove this plugin from the code base as I need the Web support. I'm looking forward to the Web support to be added.

**Comment by pixnbit** [comment]
Whoever is interested in this just try this: https://github.com/roughike/flutter_facebook_login/pull/227

It worked for me and it should be merged in to master

**Comment by dannycortesv** [comment]
@serragnoli what plugin are you using now? I can't find one that works for web

**Comment by omarbelkhodja** [comment]
@dannycortesv as explained by @pixnbit, porting to web is a work in progress. You might give it a try by setting the following in your pubspec file. (works only when your app is run in HTTPS mode).

```
  flutter_facebook_login:
    git:
      url: 'git@github.com:romulojjunior/flutter_facebook_login.git'
      ref: 'v1.3.0-web' # Check latest version
```
