### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by aboda1986** [roughike/flutter_facebook_login#85]
Google has updates all their flutter dependencies, what causes to migrate to AndroidX libs.
Unfortunately this plugin crashes after migration.

**Comment by aboda1986** [comment]
please update it to support AndroidX

**Comment by nemoryoliver** [comment]
This is a must. Thank you dev!

**Comment by mikron123** [comment]
Build fails. +1

**Comment by KammererTob** [comment]
There is an open pull request for that. Hopefully will be merged in the near future:
https://github.com/roughike/flutter_facebook_login/pull/87

**Comment by g3rrydanc3** [comment]
+1

**Comment by itsurmvk** [comment]
Please provide AndroidX Support ASAP. Thanks!

**Comment by aboda1986** [comment]
Any update dev?

**Comment by roughike** [comment]
A fix for this is now landed on master, but not on Pub just yet.

I decided to go with merging #96, as that one was close to how the official Flutter plugins were migrated to AndroidX. Seems like that approach also works better for libraries that doesn't have AndroidX support just yet.

I would love people to test this and verify that it works for you too. If everything is fine, I'll make a new major release on Pub in a couple days. Follow [these instructions to migrate your Flutter app to AndroidX](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#how-to-migrate-a-flutter-app-to-androidx) and then include the AndroidX -compatible `flutter_facebook_login` like this:

```yaml
dependencies:
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: e69fef3
```

**Comment by kentcb** [comment]
@roughike just one data point, but it works for me.

**Comment by xqwzts** [comment]
`testInstrumentationRunner` should also be changed to the androidx one:
https://github.com/roughike/flutter_facebook_login/blob/master/android/build.gradle#L29

```
    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
```

**Comment by roughike** [comment]
@xqwzts Good catch! Although it shouldn't affect production code, it shows up in the `Migrate to AndroidX...` dialog when migrating a project to AndroidX, which shouldn't happen.

Here's the latest version that has the correct testInstrumentationRunner dependency:

```yaml
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: '79ff08a'
```
